title: Software Assurance
description: This repository includes things related to the Software Assurance course at UNO
google_analytics:
show_downloads: true
theme: jekyll-theme-hacker
markdown: kramdown
